// AUTO-GENERATED by scripts/import-photos.mjs (the `about/` source folder).
// Do not edit by hand. Re-run `npm run import-photos -- --source <dir>` with an
// `about/` subfolder to regenerate.
//
// Paths to the /about sidebar photos, copied into public/about/. content.ts
// merges these onto the about page (they win over any manually-set paths), the
// same way portfolio-manifest.ts feeds the galleries. Empty until photos are
// imported, in which case the about page simply renders single-column.

export const aboutImages: string[] = [];
