// AUTO-GENERATED by scripts/import-photos.mjs.
// Do not edit by hand. Re-run `npm run import-photos -- --source <dir>` to
// regenerate after exporting fresh JPEGs from Lightroom Classic.
//
// Maps each portfolio slug to the cover image and full gallery list,
// derived from files copied into public/portfolio/<slug>/. content.ts
// merges this map onto the static portfolio metadata so adding or
// removing images is a single command instead of a manual edit.

export type PortfolioManifestEntry = {
  coverImage: string;
  images: { src: string; alt: string; width: number; height: number; blurDataURL: string }[];
};

export const portfolioManifest: Record<string, PortfolioManifestEntry> = {};
